### PR TITLE
[Refactor][web] refactor reg's datasource

### LINKED ISSUE #1822: [Refactor][web] refactor datasource manage
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor datasource manage。in dinky-web module

**note**: will be use card list to implement

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #1823: [Refactor][web] refactor The metadata center is merged into the data source by clicking to jump
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor The metadata center is merged into the data source by clicking to jump

1.register a datasource
2.click this datasource
3.Replace current page Enter metadata center

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zzm0809**
## Purpose of the pull request

refactor reg's datasource

### list
image

### added
image

#### datasource type is merge to this form
image

#### 增加焦点事件自动完成下拉 , 支持关键词搜索, 点击填充, 类似 jdbc 模版概念
image

#### tooltips
image

image

### modify
image

### delete
image

### enable
image

#### ok
image

#### error
image
image

#### tooltips
image

#### enter 
3b0995ea913f91521d26fba306b2fa3

##### status error cannot enter
 
image

##### detail page
image
image

> The remaining other functions will be carried out in the next pr

### CODE REVIEW

**Review by leechor — APPROVED** [review]
LGTM

**Comment by zhu-mingye** [comment]
done, please review

**Comment by Zzm0809** [comment]
done, please review

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
