### PR TITLE
append k8s change flink version tutorial and k8s tips

### PR DESCRIPTION
**Pull request by xiaolin84250**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by xiaolin84250** [comment]
I added a reminder

**Comment by xiaolin84250** [comment]
I added a reminder

**Review by xiaolin84250 — COMMENTED** [review]
I added a reminder

**Comment by xiaolin84250** [comment]
Have already finished.

**Comment by xiaolin84250** [comment]
Excuse me, I'm new here. Assignees clicked the wrong button.

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
