### PR TITLE
[Optimization-3932][cdc] Optimize CDCSOURCE and support sink print and mock

### LINKED ISSUE #3932: [Optimization][cdc] Optimize CDCSOURCE and support sink print and mock
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by aiwenmo**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by aiwenmo** [comment]
image

**Comment by aiwenmo** [comment]
image

**Comment by aiwenmo** [comment]
1.CDCSOURCE supports mock test.
2.Fix duplicate captured mock data.(Pic No.1)
3.Mock test supports async.(Pic No.2)
PTAL @MactavishCui

**Review by Zzm0809 — APPROVED** [review]

**Comment by MactavishCui** [comment]
LGTM

**Pull request merged**
