### PR TITLE
fix: JobConfig constructor useAutoCancel parameter pass wrong value.

### PR DESCRIPTION
**Pull request by leechor**

### CODE REVIEW

**Comment by aiwenmo** [comment]
Please check if the file named pom.xml contains the following:

`<importOrder>
                            <order>com.dlink,org.apache,java,javax,org,com,,\#</order>
                        </importOrder>`

**Comment by leechor** [comment]
> Please check if the file named pom.xml contains the following:
> 
> `<importOrder> <order>com.dlink,org.apache,java,javax,org,com,,\#</order> </importOrder>`

contain it.

**Comment by aiwenmo** [comment]
Please check if the file named pom.xml contains the following:

`<importOrder>
                            <order>com.dlink,org.apache,java,javax,org,com,,\#</order>
                        </importOrder>`

> > Please check if the file named pom.xml contains the following:
> > `<importOrder> <order>com.dlink,org.apache,java,javax,org,com,,\#</order> </importOrder>`
> 
> contain it.

This is the dependent formatting order.

**Comment by aiwenmo** [comment]
If the order is wrong after run spotless:apply, please correct it manually first.

**Comment by leechor** [comment]
> <importOrder> <order>com.dlink,org.apache,java,javax,org,com,,\#</order> </importOrder>

`
<importOrder>
                            <order>com.dlink,org.apache,java,javax,org,com,,\#</order>
                        </importOrder>
`
looks right, I will try to solve it.

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
