### PR TITLE
feat: database config and fragment variable encrypt

### LINKED ISSUE #2109: [Feature][admin,web] 全局变量新增加密选项
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

使用全局变量时，如果涉及到类似数据库密码这样的变量，新增加密选项，在数据库中以密文存储，并且前端展示时以******代替。

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanjf**
## Purpose of the pull request

Database password and fragment variable encrypt.
Refer to Flink SENSITIVE for encrypted storage when the variable name contains `password`,`secret`,`fs.azure.account.key`,`apikey`.

## Brief change log

- database password
- fragment variable value

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by zackyoungh — APPROVED** [review]
LGTM

**Comment by Zzm0809** [comment]
@ruanjf Hi , Very good pr, does the dml of H2 need to be modified synchronously?

**Comment by ruanjf** [comment]
@zhu-mingye h2 dml updated

**Review by Zzm0809 — APPROVED** [review]
LGTM

**Pull request merged**
