### PR TITLE
Optimize layout and code

### PR DESCRIPTION
**Pull request by Zzm0809**
## Purpose of the pull request

- 除登录页外 其他页脚不展示, 留出更多空间供展示与操作
- 优化代码分包结构

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by aiwenmo — APPROVED** [review]
LGTM

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by zhu-mingye** [comment]
@aiwenmo done, please review

**Comment by Zzm0809** [comment]
@aiwenmo done, please review

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
