### PR TITLE
[Optimization-1646][metadata] Optimize units test add assertion

### PR DESCRIPTION
**Pull request by mymmyy**
## Purpose of the pull request

Optimize units test add assertion #1646

## Brief change log

- dinky-metadata units test add assertion

## Verify this pull request

This change added tests and can be verified as follows:
  - *Added dinky-metadata tests assertion.*

### CODE REVIEW

**Comment by aiwenmo** [comment]
How do you think it is more appropriate to assert?

**Comment by mymmyy** [comment]
> How do you think it is more appropriate to assert?

Now it seems that the submitted test class with assertion should not be necessary to add assertion, because the test class of dinky-metadata is to test the validity of the connected code of various external data sources. the test class of dinky-core is to test the validity of the FlinkRest code. It is only convenient for developers in the development phase and not helpful when compiling and packaging. The addition of Assertion in the case of logging only enriches the means of checking the test results, and does not have a very obvious optimization to improve code performance.

I don't think it is very necessary to add assert to these test classes.
Maybe I didn't consider a more suitable assert method, can you give some suggestions?

**Comment by aiwenmo** [comment]
Sorry. At present, I can't think of how to do it. Maybe you can refer to other open source projects. thx

**Comment by leechor** [comment]
> 

the connection to other services is guaranteed according to the library unit tests, we only need to make sure invoke behavior is all right, so could [mock](https://semaphoreci.com/community/tutorials/stubbing-and-mocking-with-mockito-2-and-junit) the connection function result.

**Comment by aiwenmo** [comment]
> > 
> 
> the connection to other services is guaranteed according to the library unit tests, we only need to make sure invoke behavior is all right, so could [mock](https://semaphoreci.com/community/tutorials/stubbing-and-mocking-with-mockito-2-and-junit) the connection function result.

Can you give an example?

**Comment by leechor** [comment]
> > > 
> > 
> > 
> > the connection to other services is guaranteed according to the library unit tests, we only need to make sure invoke behavior is all right, so could [mock](https://semaphoreci.com/community/tutorials/stubbing-and-mocking-with-mockito-2-and-junit) the connection function result.
> 
> Can you give an example?

#1701

**Comment by aiwenmo** [comment]
- [X] #1701

**Pull request closed without merging**
