### PR TITLE
Fix 3636

### LINKED ISSUE #3636: [Bug] [Module Name] org.apache.flink.sql.parser.impl.ParseException: Encountered "-" When the database name contains a hyphen -, the entire database synchronizes and reports an error
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

数据库名称带横杠-时，全库同步报错
When the database name contains a dash -, a full database synchronization error is reported

2024-07-10 10:09:03.683 ERROR org.dinky.cdc.AbstractSinkBuilder(159): org.apache.flink.table.api.SqlParserException: Invalid SQL identifier VIEW_xxxxxx-xxxx_table_name.
Caused by: org.apache.flink.sql.parser.impl.ParseException: Encountered "-" at line 1, column 12.

### What you expected to happen

我期望可以支持带横杠的数据库做全库同步。
我查看了源码，可以修改 getSchemaTableNameWithUnderline 这个方法，来替换横杠为下划线，以此来支持带有横杠的数据库

I hope to support databases with dashes for full database synchronization.
I checked the source code and found that the getSchemaTableNameWithUnderline method can be modified to replace dashes with underscores to support databases with dashes.

### How to reproduce

EXECUTE CDCSOURCE jobname WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'xxxxx',
  'port' = '3306',
  'username' = 'xxxxx',
  'password' = 'xxxxx',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'server-time-zone' = 'Asia/Shanghai',
  'source.scan.incremental.snapshot.chunk.size' = '8096',
  'source.scan.snapshot.fetch.size' = '1024',
  'table-name' = 'xxxxxx-xxxx\.table_name_1,xxxxxx-xxxx\.table_name_2',
  'sink.connector' = 'starrocks',
  'sink.jdbc-url' = 'jdbc:mysql://xxxxx',
  'sink.load-url' = 'xxxxx',
  'sink.username' = 'xxxxx',
  'sink.password' = 'xxxxx',
  'sink.sink.db' = 'xxxxx',
  'sink.table.prefix' = '',
  'sink.table.lower' = 'true',
  'sink.database-name' = 'xxxxx',
  'sink.table-name' = '#{tableName}',
  'sink.sink.properties.format' = 'json',
  'sink.sink.properties.strip_outer_array' = 'true',
  'sink.sink.max-retries' = '10',
  'sink.sink.buffer-flush.interval-ms' = '5000',
  'sink.sink.parallelism' = '1'
)

### Anything else

我可以自己尝试修改一下，fork之后自己改一下，看看能不能提交一个PR

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Lordeath**
## Purpose of the pull request

fix https://github.com/DataLinkDC/dinky/issues/3636

## Brief change log

fix https://github.com/DataLinkDC/dinky/issues/3636

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by gaoyan1998** [comment]
The modification is too violent，Consider turning this feature on and off by adding parameters？

**Comment by Lordeath** [comment]
> The modification is too violent，Consider turning this feature on and off by adding parameters？

关键问题是，view里面带了横杠，后续操作一定报错，就是要回避掉这个横杠的，不管是表名还是数据库名称
The key problem is that if there is a hyphen in the view, subsequent operations will definitely report an error, that is, to avoid this hyphen, whether it is a table name or a database name

我的修改就是这样的
thats my fix：
`viewName = viewName.replaceAll("-", "_");`

**Comment by Zzm0809** [comment]
@Lordeath 请重新提一个 pr 或者 回滚掉最后一个 commit 记录

**Comment by Zzm0809** [comment]
Due to no reply for a long time, the new PR is #3833
Thank you again for your contribution

**Pull request closed without merging**
