### PR TITLE
[Feature 1101][pom] add spotless plugin

### LINKED ISSUE #1101: [Feature][pom] add spotless plugins
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add this plug-in to help improve the code format. 
 
When the code changes, run mvn spotless: apply to repair the code style

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gtk96**
## Purpose of the pull request

This pull request adds spotless plugin #1101 

## Brief change log

This pull request added spotless plugin and made spotless test on some files.

## Verify this pull request

This pull request added files and formatted some files

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zhuangchong** [comment]
Whether the two plug-ins checkstyle and spotless can keep one or not.

**Comment by gtk96** [comment]
> Whether the two plug-ins checkstyle and spotless can keep one or not.

In my experiment, there seems to be no conflict between the two. If necessary, we can delete the checkstyle.

 in addition flink cdc uses two plug-ins at the same time, and aslo we can add spotless checks in the build process.

refer link
https://github.com/ververica/flink-cdc-connectors/blob/master/pom.xml

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by aiwenmo** [comment]
Hi. Invite you to join the contributor group to discuss relevant spotless issues.

**Comment by rookiegao** [comment]
> 

Thanks for your invitation,  How can I join？

**Pull request merged**
