### PR TITLE
[2175][fix] 解决on k8s application模式下，提交任务失败时，无信息输出问题

### LINKED ISSUE #2175: [Bug] [admin] 如果on k8s application模式提交失败时控制台无任何信息
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

on k8s application模式提交失败时控制台无任何信息，此bug已修，此issue只为提pr

解决后的效果：  
image

### What you expected to happen

能打印出错误信息

### How to reproduce

* 方式一： k8s on application模式下重复提交同一个任务  
* 方式二：任务名用中文  

### Anything else

_No response_

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by seawenc**
## Purpose of the pull request

解决on k8s application模式下，提交任务失败时，无信息输出问题

测试效果：

### CODE REVIEW

**Comment by Zzm0809** [comment]
@sewenc Hi, please use english of the log.info , and you should be execute format code

**Comment by zackyoungh** [comment]
Please execute Spotless under Maven, formatting code

**Comment by aiwenmo** [comment]
Which version are you using?

**Comment by seawenc** [comment]
> Which version are you using?

dev

**Pull request closed without merging**
