### PR TITLE
[Optimization-3917][core] Optimize explain and add test

### LINKED ISSUE #3917: [Optimization][core] Optimize explain and add test
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by aiwenmo**
## Purpose of the pull request

1.Optimize explain sql to support select statement, etc.
2.Optimize get stream graph to support select statement, etc.
3.Optimize get job plan info to support select statement, etc.
4.Optimize get lineage to support select statement, etc.
5.Add test to check the new feature of statements.
6.Optimize debug task.
7.Optimize execution step tp support sort execution

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by aiwenmo** [comment]
The implementation of other Flink versions is on the way.

**Comment by aiwenmo** [comment]
@MactavishCui PTAL. Mocksink in flink 1.16,1.18,1.19, and other version is on the way.

**Comment by MactavishCui** [comment]
> @MactavishCui PTAL. Mocksink in flink 1.16,1.18,1.19, and other version is on the way.

Thanks for the heads-up. I'll have a look

**Review by Zzm0809 — APPROVED** [review]

**Comment by MactavishCui** [comment]
> > @MactavishCui PTAL. Mocksink in flink 1.16,1.18,1.19, and other version is on the way.
> 
> Thanks for the heads-up. I'll have a look

LGTM

**Pull request merged**
