### PR TITLE
[Improvement][data studio]oracle timestamp column type order is changed to precede time column

### PR DESCRIPTION
**Pull request by zhuxt2015**
…type

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by Zzm0809** [comment]
目的是为了提前匹配?

**Comment by zhuxt2015** [comment]
> 目的是为了提前匹配?

time类型在前，导致timestamp字段被匹配到time类型，而匹配不到timestamp类型

**Comment by Zzm0809** [comment]
> > 目的是为了提前匹配?
> 
> time类型在前，导致timestamp字段被匹配到time类型，而匹配不到timestamp类型

是否有更好的方案

**Comment by zhuxt2015** [comment]
> > > 目的是为了提前匹配?
> 
> > 
> 
> > time类型在前，导致timestamp字段被匹配到time类型，而匹配不到timestamp类型
> 
> 
> 
> 是否有更好的方案

目前没有其他方案

**Review by Zzm0809 — APPROVED** [review]

**Pull request merged**
