### PR TITLE
[Feature] flinkSQL 添加内置日期变量

### PR DESCRIPTION
**Pull request by dzygcc**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by aiwenmo** [comment]
请在当前代码上执行 mvn spotless:apply

**Comment by aiwenmo** [comment]
然后在IDEA里编译验证下是否还有错误

**Comment by dzygcc** [comment]
> 然后在IDEA里编译验证下是否还有错误

style fix 好了

**Comment by aiwenmo** [comment]
您好，请举个使用的例子

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by dzygcc** [comment]
> 

    'scan.partition.lower-bound'='${_CURRENT_DATE_-2}',
    'scan.partition.upper-bound'='${_CURRENT_DATE_+1}'

**Pull request merged**
