### PR TITLE
[Fix][web] Fields' value should be clear after closing edit dialog on Registration Center's Flink instance management page

### LINKED ISSUE #1344: [Bug] [WebUI] Fields' value should be clear after closing edit dialog on Registration Center's Flink instance management page
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

图片

### What you expected to happen

Don't show me the previous input content.

### How to reproduce

1. Registration Center > Clusters management > Flink instance management.
2. Click 'New' button to enter 'Cluster creation' edit dialog, input something, then close (click 'Finish' or 'Cancel' button).
3. Re-click 'New' button to enter 'Cluster creation' edit dialog, it shows me the previous input content.

### Anything else

_No response_

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wellCh4n**
… Registration Center's Flink instance management page

## Purpose of the pull request
fixed #1344 

## Brief change log

* reset form when render cluster form
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by aiwenmo** [comment]
Hi. This fix has serious problems.

**Comment by wellCh4n** [comment]
> Hi. This fix has serious problems.

Got that. How to reproduce.

**Comment by aiwenmo** [comment]
Try to create a new cluster or cluster configuration.

**Comment by wellCh4n** [comment]
> Try to create a new cluster or cluster configuration.

Okay, I reproduce that in cluster configuration. onValuesChange will invoke rednerContent() I guess. But cluster is ok right?
I will fix that ASAP.

**Comment by wellCh4n** [comment]
@aiwenmo see #1449

**Pull request merged**
