### PR TITLE
[Optimization][Data Studio]add getSchemas and getTables api

### LINKED ISSUE #3733: [Optimization][Data Studio]  Recommend display the oracle schema in pagination
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

当oracle拥有大量schema时，切换到oracle数据源时页面卡死或者占用大量cpu
image

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request

fix #3733
The information of schema and table is request in two api, and single api of getSchemasAndTables takes too long to obtain the information , which will cause the page to freeze

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by Zzm0809** [comment]
只修改后端无意义。前端调用接口还是之前的，前端是否可以同时优化

**Comment by zhuxt2015** [comment]
> 只修改后端无意义。前端调用接口还是之前的
前端不会写呀，大佬，帮忙在社区找一个前端吧

**Comment by Zzm0809** [comment]
> > 只修改后端无意义。前端调用接口还是之前的
> 前端不会写呀，大佬，帮忙在社区找一个前端吧



ok，我将来协助你完成此项优化

**Review by gaoyan1998 — APPROVED** [review]
LGTM

**Pull request merged**
