### PR TITLE
修复推送前置任务至海豚调度，在海豚调度中工作流显示异常的问题

### PR DESCRIPTION
**Pull request by cl1226**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by aiwenmo** [comment]
image

**Comment by aiwenmo** [comment]
试试这种方式可以吗

**Comment by cl1226** [comment]
可以

**Comment by aiwenmo** [comment]
> 可以

测试结果如何？

**Comment by cl1226** [comment]
经测试没问题

**Comment by aiwenmo** [comment]
欢迎提交最新代码~

**Comment by aiwenmo** [comment]
#1888

**Pull request closed without merging**
