### PR TITLE
Fix #1958 (When PK do not declare at the table head, data misalignmen…

### LINKED ISSUE #1958: [Bug] [CDCSOURCE] When PK do not declare at the table head, data misalignment occurs after synchronizing data which caused by CDCSOURCE reorders table columns by PK
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When PK do not declare at the table head, data misalignment occurs after synchronizing data which caused by CDCSOURCE reorders table columns by PK.

当 PK 列未声明在表的头部（建表语句最前面）时，由于 CDCSOURCE 处理逻辑对表的列按 PK 重新排序造成数据同步后数据错列。

### What you expected to happen

Data sync properly using CDCSOURCE mode.

### How to reproduce

Environment: Dinky 0.7.3, Flink 1.16.1, Paimon 0.4-snapshot, MySQL 8.0.29
mysql2paimon's CDCSOURCE whole library synchronization job, there is a source table with primary key column id not the first column, i.e. code, name, id, created_by, created_at.
After the data synchronization, the data value in the target table is in the wrong column, and the value of the id column of the source table is inserted into the code column of the target table.
Look at the code to find the reason is that com.dlink.trans.ddl. method.
That is, the columns of the table are reordered by primary key.

环境：Dinky 0.7.3，Flink 1.16.1，Paimon 0.4-snapshot，MySQL 8.0.29
mysql2paimon 的 CDCSOURCE 整库同步作业，有1张源表的主键列 id 不是第1列，即 code, name, id, created_by, created_at，
数据同步过去后目标表里的数据值错列了，源表 id 列的值插入到目标表 code 列了，
看代码找到的原因是 com.dlink.trans.ddl.CreateCDCSourceOperation#build 方法中调用了 com.dlink.metadata.driver.AbstractJdbcDriver#listColumnsSortByPK 方法，
即对表的列按主键重新排序了。

### Anything else

See below to find where the bug occurs by.

图片
图片

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leeoo**
…t occurs after synchronizing data which caused by CDCSOURCE reorders table columns by PK)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by aiwenmo** [comment]
dinky/dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/driver/DorisDriver.java:[126,17] cannot find symbol Column

**Review by aiwenmo — CHANGES_REQUESTED** [review]
dinky/dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/driver/DorisDriver.java:[126,17] cannot find symbol Column

**Comment by leeoo** [comment]
Sorry, I've updated this PR just now.

**Pull request merged**
