### PR TITLE
[Fix] [dinky-admin] Uniformly use '/' as the file separator.

### PR DESCRIPTION
**Pull request by Jam804**
## Purpose of the pull request

[Fix] [dinky-admin] Uniformly use '/' as the file separator.

When synchronizing the resource directory structure in local mode, different file separators may be generated due to differences in operating systems.

## Brief change log
This change added tests and can be verified as follows:

Test results ensure that the full file name can be generated using the '/' separator on both Windows and Linux systems.

### CODE REVIEW

**Comment by Jam804** [comment]
image

**Comment by Jam804** [comment]
> image

This is the result of running on Windows before the modification.

**Comment by Jam804** [comment]
@gaoyan1998 PTAL, thanks

**Comment by Jam804** [comment]
@aiwenmo PTAL, Thanks

**Review by gaoyan1998 — APPROVED** [review]
LGTM

**Pull request merged**
