### PR TITLE
refactor: delete task alias

### PR DESCRIPTION
**Pull request by Zzm0809**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by leechor — APPROVED** [review]
LGTM

**Comment by zhu-mingye** [comment]
任务列表树 布局变更：
image

提交任务使用pipelineName：
image
image

**Review by zackyoungh — APPROVED** [review]
LGTM

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
