### PR TITLE
feat: remove flink1.12

### PR DESCRIPTION
**Pull request by leechor**

### CODE REVIEW

**Comment by Zzm0809** [comment]
please remove about dinky-assembly module of flink1.12 config

**Comment by Zzm0809** [comment]
please remove about workflows/docker_build.yaml some config

**Comment by leechor** [comment]
> please remove about dinky-assembly module of flink1.12 config

Done.

**Comment by leechor** [comment]
Done

**Review by aiwenmo — APPROVED** [review]
LGTM

**Pull request merged**
