### PR TITLE
Fix wrong Python type, and format Python code.

### PR DESCRIPTION
**Pull request by leeoo**
## Purpose of the pull request

Fix wrong Python type, and format Python code.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by aiwenmo** [comment]
Please resolve conflicts.

**Comment by leechor** [comment]
> LGTM

this pr merged to 0.7 branch? @zhu-mingye maybe need 0.8's sql pr first.

**Comment by Zzm0809** [comment]
> > LGTM
> 
> this pr merged to 0.7 branch? @zhu-mingye maybe need 0.8's sql pr first.

 This pr is merged into the 0.7 branch first, and I will synchronously modify this bug at 0.8

**Comment by aiwenmo** [comment]
目录不对吧

**Pull request closed without merging**
